spring.application.name=spring-security-examples
### Enables HTTPS ###
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:certificate.p12
#server.ssl.key-store-password=12345
######
spring.datasource.url=jdbc:h2:mem:spring
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always