package com.jonas.spring_security_examples.controllers;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloController {

    //with the default configuration from Spring Security, all endpoints are secured by basic authentication: user:uuid(password).Ex.:
    //curl --verbose -u user:6dc34a17-f425-4a1e-89b4-b4257907618f http://localhost:8080/hello.
    //Behind the scenes, curl encodes the string <username>:<password> in Base64 and sends it as the value of the Authorization header prefixed with the string Basic. Ex.:
    //curl -v -H "Authorization:Basic dXNlcjo2ZGMzNGExNy1mNDI1LTRhMWUtODliNC1iNDI1NzkwNzYxOGY=" localhost:8080/hello
    //Basic authentication doesn't offer confidentiality; for this reason, we generally don't use Basic authentication with at least HTTPS
    //There are several patterns for configuring HTTPS in a system: at the application level, with use of a service mesh, or at the infrastructure level.
    //With Spring Boot you can easily enable HTTPS at the application level. But, in any of the scenarios, you need a certificate signed by a certification authority (CA)
    //Using this certificate, the client that calls the endpoint knows whether the response comes from the authentication server and that nobody intercepted the communication.
    //You can buy a certificate, but if you just want to test the application, you can generate a self-signed certificate using a tool such as OpenSSL.
    //To generate a self-signed certificate: openssl req -newkey rsa:2048 -x509 -keyout key.pem -out cert.pem -days 365
    //The command outputs two files: key.pem(the private key) and cert.pem (a public certificate). We'll use these files to generate our self-signed certificate for enabling HTTPS.
    //In most cases, the certificate is the Public Key Cryptography Standard #12 (PKCS12). Less frequently, we use a Java KeyStore (JKS) format. Let's use PKCS12 format.
    //Run this command openssl pkcs12 -export -in cert.pem -inkey key.pem -out certificate.p12 -name "certificate"
    //This command receives as input the two files generated by the first command and outputs the self-signed certificate.
    //With the certificate, you can configure HTTPS for you endpoints. Copy the certificate.p12 file into the resources folder of the Spring Boot project, and add the following lines to your application.properties:
    //spring.application.name=spring-security-examples
    //server.ssl.key-store-type=PKCS12
    //server.ssl.key-store=classpath:certificate.p12
    //server.ssl.key-store-password=12345
    //If you use a self-signed certificate, you should configure you http client (ex. curl) to skip testing the authenticity of the certificate. If the tool tests the authenticity of the certificate,
    //it won't recognize it as being authentic, and the call won't work. With curl, you use -k option to skip testing the authenticity of the certificate:
    //curl -k -u user:7203136f-a44a-4d07-8ba6-a9db3ae23226 https://localhost:8080/hello
    @GetMapping("/hello")
    public String hello() {
        return "Hello!";
    }

}
